package regis;
// Generated Jul 28, 2014 1:47:11 PM by Hibernate Tools 3.6.0



/**
 * SubscribedUsers generated by hbm2java
 */
public class SubscribedUsers  implements java.io.Serializable {


     private String username;
     private String package_;
     private Integer noOfMonths;

    public SubscribedUsers() {
    }

	
    public SubscribedUsers(String username, String package_) {
        this.username = username;
        this.package_ = package_;
    }
    public SubscribedUsers(String username, String package_, Integer noOfMonths) {
       this.username = username;
       this.package_ = package_;
       this.noOfMonths = noOfMonths;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPackage_() {
        return this.package_;
    }
    
    public void setPackage_(String package_) {
        this.package_ = package_;
    }
    public Integer getNoOfMonths() {
        return this.noOfMonths;
    }
    
    public void setNoOfMonths(Integer noOfMonths) {
        this.noOfMonths = noOfMonths;
    }




}


